const DELIVERY_LIST_DATA = [
  {
    delivery_id: "D-1A2B3C",
    order_id: "O-3F5A1C",
    customer_id: 1000,
    customer_name: "Customer 1",
    date_shipped: "2025-03-22",
    expected_delivery_date: "2025-03-24",
    delivered_date: null,
    delivery_address: "Street 1",
    delivery_fee: 300,
    selected_products: [
      {
        product_id: "P003",
        product_name: "Office Chair",
        description: "Ergonomic office chair with lumbar support",
        quantity: 2,
        unit_price: 150,
        unit_of_measure: "Piece",
        markup_price: 165,
        tax: 15,
        discount: 10,
        warranty_period: 12,
      },
      {
        product_id: "P006",
        product_name: "External Hard Drive",
        description: "1TB external SSD with USB-C connectivity",
        quantity: 1,
        unit_price: 100,
        unit_of_measure: "Piece",
        markup_price: 110,
        tax: 10,
        discount: 5,
        warranty_period: 12,
      },
      {
        product_id: "P001",
        product_name: "Laptop",
        description: "High-performance laptop with Intel i7 processor",
        quantity: 1,
        unit_price: 1436,
        unit_of_measure: "Piece",
        markup_price: 1579.6,
        tax: 143.6,
        discount: 50,
        warranty_period: 24,
      },
    ],
    shipping_fee: 300,
    total_before_discount: 18360,
    total_price: 17442,
    total_tax: 1542.48,
    warranty_fee: 1363.2,
  },
  {
    delivery_id: "D-4D5E6F",
    order_id: "O-9D3E7F",
    customer_id: 1001,
    customer_name: "Customer 2",
    date_shipped: "2025-03-23",
    expected_delivery_date: "2025-03-26",
    delivered_date: "2025-03-26",
    delivery_address: "Street 5",
    delivery_fee: 150,
    selected_products: [
      {
        product_id: "P002",
        product_name: "Standing Desk",
        description: "Adjustable height standing desk",
        quantity: 20,
        unit_price: 380,
        unit_of_measure: "Piece",
        markup_price: 418,
        tax: 38,
        discount: 10,
        warranty_period: 12,
      },
      {
        product_id: "P004",
        product_name: "Wireless Mouse",
        description: "Ergonomic wireless mouse",
        quantity: 100,
        unit_price: 45,
        unit_of_measure: "Piece",
        markup_price: 50,
        tax: 4.5,
        discount: 10,
        warranty_period: 12,
      },
    ],
    shipping_fee: 500,
    total_before_discount: 13100,
    total_price: 11895,
    total_tax: 1095.6,
    warranty_fee: 785.0,
  },
  {
    delivery_id: "D-7G8H9I",
    order_id: "O-5A1B2C",
    customer_id: 1002,
    customer_name: "Customer 3",
    date_shipped: "2025-03-24",
    expected_delivery_date: "2025-03-27",
    delivered_date: "2025-03-27",
    delivery_address: "Street 12",
    delivery_fee: 200,
    selected_products: [
      {
        product_id: "P005",
        product_name: "Monitor",
        description: "27-inch 4K UHD monitor",
        quantity: 1,
        unit_price: 500,
        unit_of_measure: "Piece",
        markup_price: 550,
        tax: 50,
        discount: 20,
        warranty_period: 24,
      },
      {
        product_id: "P007",
        product_name: "Mechanical Keyboard",
        description: "RGB backlit mechanical keyboard",
        quantity: 1,
        unit_price: 120,
        unit_of_measure: "Piece",
        markup_price: 132,
        tax: 12,
        discount: 5,
        warranty_period: 12,
      },
    ],
    shipping_fee: 700,
    total_before_discount: 19550,
    total_price: 18195.5,
    total_tax: 1725.8,
    warranty_fee: 1290.0,
  },
  {
    delivery_id: "D-9J1K2L",
    order_id: "O-8E6D4B",
    customer_id: 1003,
    customer_name: "Customer 4",
    date_shipped: "2025-03-25",
    expected_delivery_date: "2025-03-29",
    delivered_date: null,
    delivery_address: "Street 20",
    delivery_fee: 100,
    selected_products: [
      {
        product_id: "P008",
        product_name: "Smartphone",
        description: "Flagship smartphone with 256GB storage",
        quantity: 1,
        unit_price: 999,
        unit_of_measure: "Piece",
        markup_price: 1099,
        tax: 99.9,
        discount: 30,
        warranty_period: 24,
      },
    ],
    shipping_fee: 250,
    total_before_discount: 23750,
    total_price: 21000,
    total_tax: 2025.0,
    warranty_fee: 1575.0,
  },
];

export default DELIVERY_LIST_DATA;
