const INVOICE_LIST_DATA = [
  {
    invoice_id: "I-1A2B3C",
    order_id: "O-3F5A1C",
    customer_id: 1000,
    date_issued: "2025-03-21",
    due_date: "2025-04-05",
    total_before_discount: 1836,
    discount: 0,
    total_tax: 220.32,
    shipping_fee: 300,
    warranty_fee: 183.6,
    total_price: 2539.92,
    invoice_status: "Paid",
    selected_products: [
      {
        product_id: "P003",
        product_name: "Office Chair",
        description: "Ergonomic office chair with lumbar support",
        quantity: 2,
        unit_price: 150,
      },
      {
        product_id: "P006",
        product_name: "External Hard Drive",
        description: "1TB external SSD with USB-C connectivity",
        quantity: 1,
        unit_price: 100,
      },
      {
        product_id: "P001",
        product_name: "Laptop",
        description: "High-performance laptop with Intel i7 processor",
        quantity: 1,
        unit_price: 1436,
      },
    ],
  },
  {
    invoice_id: "I-4D5E6F",
    order_id: "O-9D3E7F",
    customer_id: 1001,
    date_issued: "2025-03-22",
    due_date: "2025-04-06",
    total_before_discount: 500,
    discount: 10,
    total_tax: 35.0,
    shipping_fee: 150,
    warranty_fee: 50.0,
    total_price: 585,
    invoice_status: "Pending",
    selected_products: [
      {
        product_id: "P002",
        product_name: "Standing Desk",
        description: "Adjustable height standing desk",
        quantity: 1,
        unit_price: 400,
      },
      {
        product_id: "P004",
        product_name: "Wireless Mouse",
        description: "Ergonomic wireless mouse",
        quantity: 2,
        unit_price: 50,
      },
    ],
  },
  {
    invoice_id: "I-7G8H9I",
    order_id: "O-5A1B2C",
    customer_id: 1002,
    date_issued: "2025-03-23",
    due_date: "2025-04-07",
    total_before_discount: 620,
    discount: 5,
    total_tax: 55.8,
    shipping_fee: 200,
    warranty_fee: 50.0,
    total_price: 775.8,
    invoice_status: "Paid",
    selected_products: [
      {
        product_id: "P005",
        product_name: "Monitor",
        description: "27-inch 4K UHD monitor",
        quantity: 1,
        unit_price: 500,
      },
      {
        product_id: "P007",
        product_name: "Mechanical Keyboard",
        description: "RGB backlit mechanical keyboard",
        quantity: 1,
        unit_price: 120,
      },
    ],
  },
  {
    invoice_id: "I-9J1K2L",
    order_id: "O-8E6D4B",
    customer_id: 1003,
    date_issued: "2025-03-24",
    due_date: "2025-04-08",
    total_before_discount: 999,
    discount: 15,
    total_tax: 94.65,
    shipping_fee: 100,
    warranty_fee: 60.0,
    total_price: 1153.65,
    invoice_status: "Pending",
    selected_products: [
      {
        product_id: "P008",
        product_name: "Smartphone",
        description: "Flagship smartphone with 256GB storage",
        quantity: 1,
        unit_price: 999,
      },
    ],
  },
];

export default INVOICE_LIST_DATA;
