const ORDER_LIST_DATA = [
  {
    order_id: "O-3F5A1C",
    customer_id: 1000,
    customer_name: "Tech Solutions Inc.",
    date_issued: "2025-03-21",
    quotation_id: "Q-781A84",
    selected_address: "Street 1",
    selected_delivery_date: "2025-03-24",
    discount: 0,
    selected_products: [
      {
        product_id: "P003",
        product_name: "Office Chair",
        description: "Ergonomic office chair with lumbar support",
        quantity: 2,
        unit_price: 150,
      },
      {
        product_id: "P006",
        product_name: "External Hard Drive",
        description: "1TB external SSD with USB-C connectivity",
        quantity: 1,
        unit_price: 100,
      },
      {
        product_id: "P001",
        product_name: "Laptop",
        description: "High-performance laptop with Intel i7 processor",
        quantity: 1,
        unit_price: 1436,
      },
    ],
    shipping_fee: 300,
    total_before_discount: 1836,
    total_price: 2539.92,
    total_tax: 220.32,
    warranty_fee: 183.6,
  },
  {
    order_id: "O-9D3E7F",
    customer_id: 1001,
    customer_name: "Global Enterprises Ltd.",
    date_issued: "2025-03-22",
    quotation_id: "Q-9B2C6D",
    selected_address: "Street 5",
    selected_delivery_date: "2025-03-26",
    discount: 10,
    selected_products: [
      {
        product_id: "P002",
        product_name: "Standing Desk",
        description: "Adjustable height standing desk",
        quantity: 1,
        unit_price: 400,
      },
      {
        product_id: "P004",
        product_name: "Wireless Mouse",
        description: "Ergonomic wireless mouse",
        quantity: 2,
        unit_price: 50,
      },
    ],
    shipping_fee: 150,
    total_before_discount: 500,
    total_price: 585,
    total_tax: 35.0,
    warranty_fee: 50.0,
  },
  {
    order_id: "O-5A1B2C",
    customer_id: 1002,
    customer_name: "NextGen Tech Corp.",
    date_issued: "2025-03-23",
    quotation_id: "Q-4F2D9A",
    selected_address: "Street 12",
    selected_delivery_date: "2025-03-27",
    discount: 5,
    selected_products: [
      {
        product_id: "P005",
        product_name: "Monitor",
        description: "27-inch 4K UHD monitor",
        quantity: 1,
        unit_price: 500,
      },
      {
        product_id: "P007",
        product_name: "Mechanical Keyboard",
        description: "RGB backlit mechanical keyboard",
        quantity: 1,
        unit_price: 120,
      },
    ],
    shipping_fee: 200,
    total_before_discount: 620,
    total_price: 775.8,
    total_tax: 55.8,
    warranty_fee: 50.0,
  },
  {
    order_id: "O-8E6D4B",
    customer_id: 1003,
    customer_name: "Innovatech Industries",
    date_issued: "2025-03-24",
    quotation_id: "Q-6C3F1B",
    selected_address: "Street 20",
    selected_delivery_date: "2025-03-29",
    discount: 15,
    selected_products: [
      {
        product_id: "P008",
        product_name: "Smartphone",
        description: "Flagship smartphone with 256GB storage",
        quantity: 1,
        unit_price: 999,
      },
    ],
    shipping_fee: 100,
    total_before_discount: 999,
    total_price: 1153.65,
    total_tax: 94.65,
    warranty_fee: 60.0,
  },
];

export default ORDER_LIST_DATA;
