export const PRODUCTS_DATA = [
  {
    product_id: "P001",
    product_name: "Laptop",
    description: "High-performance laptop with Intel i7 processor",
    unit_of_measure: "Piece",
    warranty_period: 24,
    unit_price: 1200.0,
    markup_price: 1440.0,
  },
  {
    product_id: "P002",
    product_name: "Smartphone",
    description: "Flagship smartphone with OLED display",
    unit_of_measure: "Piece",
    warranty_period: 12,
    unit_price: 800.0,
    markup_price: 960.0,
  },
  {
    product_id: "P003",
    product_name: "Office Chair",
    description: "Ergonomic office chair with lumbar support",
    unit_of_measure: "Piece",
    warranty_period: 36,
    unit_price: 150.0,
    markup_price: 180.0,
  },
  {
    product_id: "P004",
    product_name: "Wireless Keyboard",
    description: "Bluetooth keyboard with mechanical keys",
    unit_of_measure: "Piece",
    warranty_period: 18,
    unit_price: 70.0,
    markup_price: 84.0,
  },
  {
    product_id: "P005",
    product_name: "LED Monitor",
    description: "27-inch Full HD monitor with IPS display",
    unit_of_measure: "Piece",
    warranty_period: 24,
    unit_price: 250.0,
    markup_price: 300.0,
  },
  {
    product_id: "P006",
    product_name: "External Hard Drive",
    description: "1TB external SSD with USB-C connectivity",
    unit_of_measure: "Piece",
    warranty_period: 36,
    unit_price: 180.0,
    markup_price: 216.0,
  },
  {
    product_id: "P007",
    product_name: "Coffee Maker",
    description: "Automatic coffee maker with timer function",
    unit_of_measure: "Piece",
    warranty_period: 12,
    unit_price: 90.0,
    markup_price: 108.0,
  },
  {
    product_id: "P008",
    product_name: "Air Conditioner",
    description: "Split-type air conditioner with inverter technology",
    unit_of_measure: "Unit",
    warranty_period: 60,
    unit_price: 900.0,
    markup_price: 1080.0,
  },
  {
    product_id: "P009",
    product_name: "Projector",
    description: "4K UHD projector with HDR support",
    unit_of_measure: "Piece",
    warranty_period: 24,
    unit_price: 600.0,
    markup_price: 720.0,
  },
  {
    product_id: "P010",
    product_name: "Gaming Mouse",
    description: "High DPI gaming mouse with RGB lighting",
    unit_of_measure: "Piece",
    warranty_period: 12,
    unit_price: 50.0,
    markup_price: 60.0,
  },
];
