export const PRODUCTS_DATA = [
  {
    product_id: "P001",
    product_name: "Laptop",
    description: "High-performance laptop with Intel i7 processor",
    unit_of_measure: "Piece",
    warranty_period: 24,
  },
  {
    product_id: "P002",
    product_name: "Smartphone",
    description: "Flagship smartphone with OLED display",
    unit_of_measure: "Piece",
    warranty_period: 12,
  },
  {
    product_id: "P003",
    product_name: "Office Chair",
    description: "Ergonomic office chair with lumbar support",
    unit_of_measure: "Piece",
    warranty_period: 36,
  },
  {
    product_id: "P004",
    product_name: "Wireless Keyboard",
    description: "Bluetooth keyboard with mechanical keys",
    unit_of_measure: "Piece",
    warranty_period: 18,
  },
  {
    product_id: "P005",
    product_name: "LED Monitor",
    description: "27-inch Full HD monitor with IPS display",
    unit_of_measure: "Piece",
    warranty_period: 24,
  },
  {
    product_id: "P006",
    product_name: "External Hard Drive",
    description: "1TB external SSD with USB-C connectivity",
    unit_of_measure: "Piece",
    warranty_period: 36,
  },
  {
    product_id: "P007",
    product_name: "Coffee Maker",
    description: "Automatic coffee maker with timer function",
    unit_of_measure: "Piece",
    warranty_period: 12,
  },
  {
    product_id: "P008",
    product_name: "Air Conditioner",
    description: "Split-type air conditioner with inverter technology",
    unit_of_measure: "Unit",
    warranty_period: 60,
  },
  {
    product_id: "P009",
    product_name: "Projector",
    description: "4K UHD projector with HDR support",
    unit_of_measure: "Piece",
    warranty_period: 24,
  },
  {
    product_id: "P010",
    product_name: "Gaming Mouse",
    description: "High DPI gaming mouse with RGB lighting",
    unit_of_measure: "Piece",
    warranty_period: 12,
  },
];
