const TICKET_LIST_DATA = [
  {
    ticket_id: "TCKT-001",
    customer_id: "CUST-001",
    customer_name: "John Doe",
    created_at: "2023-09-01",
    priority: "High",
    status: "Open",
    employee_id: "EMP-001",
    employee_name: "Jane Smith",
    subject: "Issue with product",
    description: "The product is not functioning as expected.",
  },
  {
    ticket_id: "TCKT-002",
    customer_id: "CUST-002",
    customer_name: "Alice Johnson",
    created_at: "2023-09-03",
    priority: "Medium",
    status: "In Progress",
    employee_id: "EMP-002",
    employee_name: "Michael Brown",
    subject: "Billing problem",
    description: "Incorrect charges appeared on the invoice.",
  },
  {
    ticket_id: "TCKT-003",
    customer_id: "CUST-003",
    customer_name: "Bob Lee",
    created_at: "2023-09-05",
    priority: "Low",
    status: "Closed",
    employee_id: "EMP-003",
    employee_name: "Sara White",
    subject: "Feature request",
    description: "Requesting a dark mode option for the application.",
  },
  {
    ticket_id: "TCKT-004",
    customer_id: "CUST-004",
    customer_name: "Emma Watson",
    created_at: "2023-09-06",
    priority: "High",
    status: "Open",
    employee_id: "EMP-004",
    employee_name: "Liam Green",
    subject: "Login issues",
    description: "Unable to log in with the provided credentials.",
  },
  {
    ticket_id: "TCKT-005",
    customer_id: "CUST-005",
    customer_name: "David Kim",
    created_at: "2023-09-07",
    priority: "Medium",
    status: "Pending",
    employee_id: "EMP-001",
    employee_name: "Jane Smith",
    subject: "Order not received",
    description: "Customer did not receive their order after 2 weeks.",
  },
  {
    ticket_id: "TCKT-006",
    customer_id: "CUST-006",
    customer_name: "Linda Park",
    created_at: "2023-09-09",
    priority: "High",
    status: "In Progress",
    employee_id: "EMP-002",
    employee_name: "Michael Brown",
    subject: "Account suspension",
    description: "Customer's account was suspended without notice.",
  },
  {
    ticket_id: "TCKT-007",
    customer_id: "CUST-007",
    customer_name: "Chris Evans",
    created_at: "2023-09-10",
    priority: "Low",
    status: "Resolved",
    employee_id: "EMP-005",
    employee_name: "Olivia Stone",
    subject: "Refund request",
    description: "Customer is requesting a refund for a canceled order.",
  },
  {
    ticket_id: "TCKT-008",
    customer_id: "CUST-008",
    customer_name: "Sophia Miller",
    created_at: "2023-09-12",
    priority: "Medium",
    status: "Open",
    employee_id: "EMP-003",
    employee_name: "Sara White",
    subject: "App crash",
    description: "The mobile app crashes upon opening.",
  },
  {
    ticket_id: "TCKT-009",
    customer_id: "CUST-009",
    customer_name: "Mark Ruffalo",
    created_at: "2023-09-13",
    priority: "High",
    status: "Open",
    employee_id: "EMP-006",
    employee_name: "Daniel King",
    subject: "Data not syncing",
    description: "Customer's data is not syncing across devices.",
  },
  {
    ticket_id: "TCKT-010",
    customer_id: "CUST-010",
    customer_name: "Natalie Portman",
    created_at: "2023-09-15",
    priority: "Low",
    status: "Closed",
    employee_id: "EMP-004",
    employee_name: "Liam Green",
    subject: "General inquiry",
    description: "Customer has general questions about the service.",
  },
];

export default TICKET_LIST_DATA;
